version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../
      dockerfile: ./Docker/frontend/Dockerfile
    volumes:
      - ../frontend/:/frontend/result_build/

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_volume:/backend/django_static
      - media_volume:/backend/django_media

  backend:
    build:
      context: ../
      dockerfile: ./Docker/backend/Dockerfile
    restart: unless-stopped
    entrypoint: /backend/start/wsgi-entrypoint.sh
    volumes:
      - static_volume:/backend/django_static
      - media_volume:/backend/django_media
    depends_on:
      - db
    env_file:
      - ../backend/.env

volumes:
  static_volume:
  media_volume:
  postgres_data:
