# Generated by Django 3.2.5 on 2021-07-11 11:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ('recipe__name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента', max_length=70, verbose_name='Ингреиент')),
                ('measurement_unit', models.CharField(choices=[('кг', 'кг'), ('г', 'г')], default='г', help_text='Выберите единицу измерения', max_length=2, verbose_name='Единица изменения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ('recipe__name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(help_text='Выберите изображение', upload_to='', verbose_name='Картинка')),
                ('text', models.CharField(help_text='Опишите рецепт', max_length=1000, verbose_name='Текстовое описание')),
                ('cooking_time', models.SmallIntegerField(help_text='Укажите время приготовления в минутах', verbose_name='Время приготовления(минуты)')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Рецепт-ингредиент',
                'verbose_name_plural': 'Рецепты-ингредиенты',
                'ordering': ('recipe__name',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=50, verbose_name='Название тега')),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Введите цвет тега', max_length=18, verbose_name='Цвет')),
                ('slug', models.CharField(help_text='Введите название слаг тега', max_length=50, verbose_name='Название слаг тега')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
    ]
