# Generated by Django 3.2.5 on 2021-07-10 08:47

import colorfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента', max_length=70, verbose_name='Ингреиент')),
                ('measurement_unit', models.CharField(choices=[('кг', 'кг'), ('г', 'г')], default='г', help_text='Выберите единицу измерения', max_length=2, verbose_name='Единица изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=50, verbose_name='Название тега')),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Введите цвет тега', max_length=18, verbose_name='Цвет')),
                ('slug', models.CharField(help_text='Введите название слаг тега', max_length=50, verbose_name='Название слаг тега')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(help_text='Выберите изображение', upload_to='', verbose_name='Картинка')),
                ('text', models.CharField(help_text='Опишите рецепт', max_length=1000, verbose_name='Текстовое описание')),
                ('cooking_time', models.SmallIntegerField(help_text='Укажите время приготовления в минутах', verbose_name='Время приготовления(минуты)')),
                ('author', models.ForeignKey(help_text='Укажите автора рецепта', on_delete=models.SET('Пользователь удалён'), to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ManyToManyField(help_text='Укажите ингредиенты и их количество', to='recipes.Ingredient', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(help_text='Выберите один или несколько тегов', to='recipes.Tag', verbose_name='Теги')),
            ],
        ),
    ]
